 stBasic     = 0;
 stExtend    = 1;


 fkPhysical  = 0;
 fkReal      = 1;
 fkFake      = 2;
 fkCalculite = 3;

 coSysHierarchyName = 'Виртуальный словарь';
 coVHierarchyName = 'VHierarchy: Базовая иерархия';
 
 evNone         = 0;
 evAfterInsert  = 1;
 evBeforeUpdate =2;
 evAfterUpdate  =3;
 evBeforDelete  =4;
 evcanDelete    =5;
 evPosChange    =6;


 fmCreate = 0;
 fmAppend = 1;
 fmOpen  = 2;

 scrUpdate           = 100;
 scrUpdateBetween    = 101;
 scrUpdateValues     = 102;
 scrFromList         = 103;
 scrEditSQL          = 104;
 scrSQL               = 105;
 scrOneFromList       = 106;
 scrInsertFilter      = 107;
 scrSetAndOr          = 108;
 scrSetFieldOperation = 109;
 scrValue             = 110;
 scrBetween           = 111;
 scrValues            = 112;
