   modView              = 0;
   modSelectList        = 16;       
   modSelectNode        = 32;
   modSelectUp          = 48;
   modSelectListNotExit = 64;       

   coClassSegmentName  = 'Classifiers';

   coDescrTuneName     = 'Настройки дескрипторов';
   coHierTuneName      = 'Настройки иерархий';
   coFieldTuneName     = 'Настройки полей';

   coStatHierarchyName = 'Статус-константы';
   coHelpHierarchyName = 'Help-константы';

   coSystemHierarchy   = 0;
   coApplyHierarchy    = 1;
   coUserHierarchy     = 2;

