
  cgxlOk                        =  0;

  cgxlErrOpenExcel              =  1;
  cgxlErrCloseExcel             =  2;
  cgxlErrConnectExcel           =  3;
  cgxlErrDisConnectExcel        =  4;
  cgxlErrDisplayAlerts          =  5;

  cgxlErrAddWorkBook            = 21;
  cgxlErrOpenWorkBook           = 22;
  cgxlErrSaveWorkBook           = 23;
  cgxlErrSaveAsWorkBook         = 24;
  cgxlErrCloseWorkBook          = 25;
  cgxlErrGetWorkBooksCount      = 26;
  cgxlErrSetActiveWorkBook      = 27;
  cgxlErrGetActiveWorkBook      = 28;

  cgxlErrAddSheet               = 41;
  cgxlErrDeleteSheet            = 42;
  cgxlErrSetActiveSheet         = 43;
  cgxlErrSetSheetName           = 44;
  cgxlErrGetSheetName           = 45;
  cgxlErrGetSheetsCount         = 46;

  cgxlErrInsertRange            = 61;
  cgxlErrDeleteRange            = 62;
  cgxlErrGetUsedRange           = 63;

  cgxlErrDelRangeByName         = 71;
  cgxlErrSetRangeName           = 72;
  cgxlErrGetRangeByName         = 73;
  cgxlErrDelRangeName           = 74;
  cgxlErrGetRangeNamesCount     = 75;

  cgxlErrSetCellValue           = 91;
  cgxlErrSetCellFormula         = 92;
  cgxlErrGetCellValue           = 93;

  cgxlErrSetFontSize            = 111;
  cgxlErrSetFontColor           = 112;
  cgxlErrSetBackColor           = 112;
  cgxlErrSetFontStyle           = 113;

  cgxlErrFreeze                 = 131;
  cgxlErrUnFreeze               = 132;
  cgxlErrSetRowHeight           = 133;
  cgxlErrSetColumnWidth         = 134;
  cgxlErrFrameCells             = 135;
  cgxlErrShrinkCells            = 136;
  cgxlErrMergeCells             = 137;
  cgxlErrAutoFit                = 138;
  cgxlErrWrapText               = 139;
  cgxlErrAlignCells             = 140;
  cgxlErrSetNumberFormat        = 141;
  cgxlErrCopyToBuff             = 142;
  cgxlErrPasteFormatFromBuff    = 143;
  cgxlErrCopyExtFormat          = 144;
  cgxlErrClearRangeContents     = 145;
  cgxlErrClearRangeFormats      = 146;
  cgxlErrClearRangeComments     = 147;
  cgxlErrSetCellIndentLevel     = 148;

  cgxlErrGetComment             = 171;
  cgxlErrAddComment             = 172;

  cgxlErrImportModule           = 201;
  cgxlErrRunMacro               = 202;
  cgxlErrAddInsInstal           = 203;

  cgxlErrSeparator              = 215;

  cgxlErrCreateMatrix           = 221;
  cgxlErrFreeMatrix             = 222;
  cgxlErrClearMatrix            = 223;
  cgxlErrWriteToMatrix          = 224;
  cgxlErrReadFromMatrix         = 225;
  cgxlErrReadMatrixFromExcel    = 226;
  cgxlErrWriteMatrixToExcel     = 227;

  cgxlErrCentimetersToPoints      = 250;
  cgxlErrInchesToPoints           = 251;
  cgxlErrPageSetupSetLeftMargin   = 252;
  cgxlErrPageSetupSetRightMargin  = 253;
  cgxlErrPageSetupSetTopMargin    = 254;
  cgxlErrPageSetupSetBottomMargin = 255;
  cgxlErrPageSetupSetHeaderMargin = 256;
  cgxlErrPageSetupSetFooterMargin = 257;
  cgxlErrPageSetupSetOrientation  = 258;
  cgxlErrPageSetupSetPaperSize    = 259;

