  DWExporterIfcName = 'dw_Exporter';
  DWDataExporterIfcName = 'dwDataExport';
  DWExecSemaphore = 'DWSemaphore_Run';
  DWEmptyStringValue = 'Без указания';

  DWDataExportSection = 'DataExport';

  dwMaxFieldNameLength = 128;
  dwMaxStrFieldLength = 243;

  _FileColumnSeparator = ''#9;

  qsPassive = 0;
  qsActive = 1;
  qsExecute = 2;
  qsPaused = 3;
  qsIncomplete = 4;
  qsComplete = 5;

  jsWaiting = 0;
  jsDone = 1;
  jsError = 2;
  jsArchive = 3;

  jsjWaiting = 0;
  jsjExecute = 1;
  jsjDone = 2;
  jsjError = 3;
  jsjBreaked = 4;
  jsjTerminated = 5;
  jsjCancelled = 6;

  qrpNextRun = 0;
  qrpOneRun  = 1;
  qrpNextDay = 2;
  qrpNextWeek = 3;
  qrpNextMonth = 4;

  dnBegin = 1;
  dnEnd = 2;