//ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
//บ                     (c) 2000 ชฎเฏฎเ ๆจ๏ €€’€                         บ
//บ เฎฅชโ        : €€’€                                                 บ
//บ ‘จแโฅฌ        : ”จญ ญแฎขฎฅ ฏซ ญจเฎข ญจฅ                                   บ
//บ ฅเแจ๏        : 5.80                                                      บ
//บ  งญ ็ฅญจฅ    : ฎญแโ ญโ๋ คซ๏ เ กฎโ๋ แ FpCube                             บ
//บ โขฅโแโขฅญญ๋ฉ : ฎงคญฅข €ซฅชแ ญคเ                                         บ
//ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

  AxisXID = 0;
  AxisYID = 1;

  FpCubeType_Memory          = 0;
  FpCubeType_Ext_DB          = 1;

  FpCubeCellFlag_IsAgrAn     = 1;
  FpCubeCellFlag_IsAgrHierAn = 2;
  FpCubeCellFlag_IsDDLeaf    = 4;

  FpCube_AgrAnID = 0;

  FpCubeDimFlag_DefaultTopRule     = 0;
  FpCubeDimFlag_AutoAddTopOnly     = 1;
  FpCubeDimFlag_AutoAddTopSub      = 2;
