Const
  // Константы для перечня полей в настройках алгоритма
  // пересчета полей путевого листа

  // первая группа полей
  cppExitCh   = 1;
  cppExitDn   = 2;
  cppSpeedExi = 3;
  cppNpVirVal = 4;

  // вторая группа полей
  cppReturnCh = 1;
  cppReturnDn = 2;
  cppSpeedRet = 3;
  cppFkVirVal = 4;

  // третья группа полей
  cppTimeLoad    = 1;
  cppTimeStop    = 2;
  cppTimeRep     = 3;
  cppTimeEngine  = 4;
  cppTimeVolume0 = 5;
  cppTimeHeat    = 6;
  cppTimeSpec    = 7;
  cppTimePg      = 8;

  // четвертая группа полей
  cppProbegAll  = 1;
  cppProbegGr   = 2;
  cppProbegV    = 3;
  cppGruzTn     = 4;
  cppGruzTnKm   = 5;
  cppKoffProbeg = 6;
  cppProbeg2    = 7;
  cppVolWrk     = 8;
