   trRolesHierName        = 'Роли и права';
   trUsersHierName        = 'Пользователи';

   trEntityArea           = 0;
   trInterfaceArea        = 1;
   trFieldArea            = 2;

   trFullControl          = 0;
   trScanEntity           = 1;
   trInsertEntity         = 2;
   trUpdateCurrentVersion = 4;
   trUpdateSaveVersion    = 8;
   trDeleteEntity         = 16;
   trPurgeEntity          = 32;
   trRunInterface         = 1;
   trViewField            = 1;
   trChangeField          = 2;


